import {
    Activity,
    BookOpen,
    Boxes,
    Braces,
    Briefcase,
    Calendar,
    CheckCircle,
    Cloud,
    Code,
    Cpu,
    Database,
    FlaskConical,
    GitBranch,
    GraduationCap,
    Layers,
    Leaf,
    LineChart,
    MapPin,
    Network,
    Server,
    Settings,
    Shield,
    Users,
    Lightbulb,
    Heart,
    Coffee,
    Phone,
    Mail,
    Quote,
    Menu,
    X,
    Github,
    Linkedin,
    User,
    MessageSquare,
    Loader2,
    CheckCircle2,
    Mic,
    Star,
    Globe,
    ExternalLink,
} from "lucide-react";

export const techIconMap: Record<string, JSX.Element> = {
    Java: <Code className="w-4 h-4"/>,
    "Spring Boot": <Leaf className="w-4 h-4"/>,
    ".NET Core": <Server className="w-4 h-4"/>,

    Microservices: <Boxes className="w-4 h-4"/>,
    "System Architecture": <Layers className="w-4 h-4"/>,
    "BFF Architecture": <Network className="w-4 h-4"/>,

    "REST APIs": <Braces className="w-4 h-4"/>,
    GraphQL: <Network className="w-4 h-4"/>,
    "System Integration": <Network className="w-4 h-4"/>,

    PostgreSQL: <Database className="w-4 h-4"/>,
    "SQL Server": <Database className="w-4 h-4"/>,
    "Oracle DB": <Database className="w-4 h-4"/>,

    "Real-time Systems": <Activity className="w-4 h-4"/>,
    Analytics: <LineChart className="w-4 h-4"/>,
    "Performance Optimization": <Activity className="w-4 h-4"/>,

    IoT: <Cpu className="w-4 h-4"/>,
    "Edge Processing": <Cpu className="w-4 h-4"/>,
    "PyTorch/TensorFlow": <Cloud className="w-4 h-4"/>,
    CNN: <Cpu className="w-4 h-4"/>,
    "Model Evaluation": <LineChart className="w-4 h-4"/>,

    Publications: <BookOpen className="w-4 h-4"/>,
    "Applied ML": <FlaskConical className="w-4 h-4"/>,
    "Peer Reviewer": <Shield className="w-4 h-4"/>,
    "Academic Track": <GraduationCap className="w-4 h-4"/>,
    "Industry Track": <Briefcase className="w-4 h-4"/>,

    "Backend Development": <Server className="w-8 h-8"/>,
    "Frontend Development": <Code className="w-8 h-8"/>,
    "Database Management": <Database className="w-8 h-8"/>,
    "DevOps & Tools": <Cloud className="w-8 h-8"/>,
    "Workflow & Best Practices": <Users className="w-8 h-8"/>,

    "Spring Security": <Shield className="w-4 h-4"/>,
    "RESTful APIs": <Boxes className="w-4 h-4"/>,

    React: <Code className="w-4 h-4"/>,
    JavaScript: <Code className="w-4 h-4"/>,
    TypeScript: <Code className="w-4 h-4"/>,
    HTML5: <Code className="w-4 h-4"/>,
    CSS3: <Code className="w-4 h-4"/>,
    Thymeleaf: <Code className="w-4 h-4"/>,

    MySQL: <Database className="w-4 h-4"/>,
    MongoDB: <Database className="w-4 h-4"/>,
    "SQL Optimization": <Settings className="w-4 h-4"/>,
    "Database Design": <Settings className="w-4 h-4"/>,

    Docker: <Cloud className="w-4 h-4"/>,
    Git: <GitBranch className="w-4 h-4"/>,
    "CI/CD": <Settings className="w-4 h-4"/>,
    Maven: <Settings className="w-4 h-4"/>,
    Gradle: <Settings className="w-4 h-4"/>,
    Jenkins: <Settings className="w-4 h-4"/>,

    Practice: <CheckCircle className="w-5 h-5 text-primary"/>,

    Experience: <Briefcase className="w-6 h-6 text-gray-700"/>,
    Calendar: <Calendar className="w-4 h-4"/>,
    Location: <MapPin className="w-4 h-4"/>,

    SOAP: <Server className="w-4 h-4"/>,
    REST: <Braces className="w-4 h-4"/>,
    OAuth2: <Shield className="w-4 h-4"/>,

    JavaEE: <Code className="w-4 h-4"/>,

    UML: <Layers className="w-4 h-4"/>,

    "OOP": <Boxes className="w-4 h-4"/>,
    "Data Structures": <Database className="w-4 h-4"/>,

    "Academic Research": <BookOpen className="w-4 h-4"/>,

    "Data Science": <LineChart className="w-5 h-5" />,
    "Machine Learning": <FlaskConical className="w-5 h-5" />,
    "Artificial Intelligence": <Cpu className="w-5 h-5" />,
    "Software Development Methodologies": <Settings className="w-5 h-5" />,

    Mentoring: <Users className="w-8 h-8 text-blue-600" />,
    "Academic Collaboration": <BookOpen className="w-8 h-8 text-green-600" />,
    Wellness: <Heart className="w-8 h-8 text-red-600" />,
    Learning: <Lightbulb className="w-8 h-8 text-purple-600" />,
    Phone: <Phone className="w-4 h-4 text-gray-500" />,
    Mail: <Mail className="w-4 h-4 text-gray-500" />,
    Quote: <Quote className="w-5 h-5 text-primary absolute bg-white rounded-full shadow-sm p-1" />,
    Menu: <Menu className="h-6 w-6" />,
    Close: <X className="h-6 w-6" />,
    Project: <Code className="w-6 h-6 text-primary" />,

    "Academic CV": <BookOpen className="w-5 h-5" />,
    "Industry Resume": <Briefcase className="w-5 h-5" />,
    LinkedIn: <Linkedin className="w-5 h-5 mr-2" />,
    GitHub: <Github className="w-5 h-5 mr-2" />,
    "Google Scholar": <GraduationCap className="w-5 h-5 mr-2" />,
    Email: <Mail className="w-5 h-5 mr-2" />,
    User: <User className="w-4 h-4" />,
    Message: <MessageSquare className="w-4 h-4" />,
    Loading: <Loader2 className="w-4 h-4 animate-spin" />,
    Success: <CheckCircle2 className="w-4 h-4" />,
    "Inquiry Academic": <GraduationCap className="w-4 h-4" />,
    "Inquiry Industry": <Briefcase className="w-4 h-4" />,
    "Inquiry Other": <MessageSquare className="w-4 h-4" />,
    Privacy: <Shield className="w-5 h-5" />,
    Speaker: <Mic className="w-6 h-6 text-primary" />,
    Leadership: <Users className="w-6 h-6 text-primary" />,
    Community: <Users className="w-6 h-6 text-primary" />,
    Activity: <Star className="w-6 h-6 text-primary" />,
    Degree: <GraduationCap className="w-6 h-6 text-blue-600" />,
    International: <Globe className="w-6 h-6 text-green-600" />,
    Achievement: <Star className="w-6 h-6 text-yellow-600" />,
    ExternalLink: <ExternalLink className="w-3 h-3" />,
};
